### ISSUE TITLE
All channels not working 

### ISSUE THREAD

**Issue by AqFad2811** [samleong123/tonton_dailymotion_php#10]
Hey, seems like all of the channels are not working anymore, when i go to the m3u page, it says access denied.

**Comment by samleong123** [comment]
will fix this soon

**Comment by samleong123** [comment]
Ok for now Dailymotion implemented IP Bind directly on their API

Example : 
If I use 115.164.87.133 (Digi Roaming IP) to request the API of Dailymotion to generate TV3's HLS , i can only use the same IP to request the HLS manifest or else i get 403

As you can see here , i can get the HLS manifest if the request IP is same with the API's IP 

<img width="1788" alt="Screenshot 2022-10-23 at 3 30 51 PM" src="https://user-images.githubusercontent.com/58818070/197380072-ef21355f-5c4c-4613-ab98-5a73dc99220e.png">

I will get 403 on the HLS manifest if i use another IP to request it
<img width="1788" alt="Screenshot 2022-10-23 at 3 31 24 PM" src="https://user-images.githubusercontent.com/58818070/197380106-32b5457c-d15f-48d4-ab7b-1780b1e716c7.png">

The problem is here , the procedure of getting HLS manifest URL (requesting the API) is done on my server's IP (TIME MY) , last time they didn't implement IP bind on the HLS manifest , but now if they implement , the HLS manifest URL generated signature mismatch with the request IP , so they will deny and return 403.

Temp solution : 
use unifiPlayTV first , until anyone find a solution

Sorry for the inconvenience caused
Replying using Digi's 4G roaming on Singtel (
![WhatsApp Image 2022-10-23 at 3 39 27 PM](https://user-images.githubusercontent.com/58818070/197380292-5ce71cec-c2a6-459d-ab27-b4108d2dee55.jpeg)

**Comment by Kendo09** [comment]
Hi Sam, how do I login to unifiplaytv on my smart TV when I'm not unifi user? Facebook login only allow to use on mobile phone

**Comment by AqFad2811** [comment]
> Hi Sam, how do I login to unifiplaytv on my smart TV when I'm not unifi user? Facebook login only allow to use on mobile phone

You can't use phone number/Facebook to login into Unifi TV (Smart TV/Android TV) app, you NEED to had an Unifi TV account to login.

**Comment by samleong123** [comment]
> Hey, seems like all of the channels are not working anymore, when i go to the m3u page, it says access denied.

Solution : Use your own devices with Docker and run the container with my image 
Details here : [https://github.com/samleong123/mediaprima_dailymotion_docker](https://github.com/samleong123/mediaprima_dailymotion_docker)

This repo will be archived and become deprecated , please refer to this [new](https://github.com/samleong123/mediaprima_dailymotion_docker) repo that uses Docker
